spring:
  datasource:
    url: jdbc:h2:mem:dbtest
    username: test
    password: 123456
    driver-class-name: org.h2.Driver
    platform: h2
    #schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true